spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prac
    password: kiseok
    username: kiseok
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true